### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by digitalhobo** [realtime-framework/RCTRealtimeMessaging#4]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SRWebSocket", referenced from:
      objc-class-ref in libRCTRealtimeMessaging.a(OrtcClient.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ghost** [comment]
I experienced the same thing, seems that its not compatible with 0.6.0 yet.
Refer here https://groups.google.com/forum/#!topic/realtime-framework/MUqm_ga8Dp8

**Comment by realtime-framework** [comment]
There is in fact a compatibility issue with reactive native 0.6.0 due to a WebSocket library refactor made my Facebook, renaming the SocketRocket symbols.

We are working on a new release to fix this (to be released probably tomorrow July 3rd)
