### ISSUE TITLE
Errors after npm install

### ISSUE THREAD

**Issue by JakeRawr** [realtime-framework/RCTRealtimeMessaging#6]
After npm install, I got a bunch of errors. 

I am running the latest release react-native 0.9.0

here are the errors from Chrome Dev Tool:

<img width="1263" alt="screen shot 2015-08-25 at 11 57 30 am" src="https://cloud.githubusercontent.com/assets/7199499/9476263/8b3e1484-4b20-11e5-91e6-830c86b34cb4.png">
<img width="1262" alt="screen shot 2015-08-25 at 11 57 42 am" src="https://cloud.githubusercontent.com/assets/7199499/9476264/900bc45c-4b20-11e5-8093-c88465802797.png">

The error occurred right after I `npm install --save react-native-realtimemessaging-ios`
If you need more info, I'm happy to reply more

**Comment by realtime-framework** [comment]
Could you send us the errors? 
It would help a lot. Also let us know the exact React Native version you're using.
Thanks.

**Comment by JakeRawr** [comment]
Hi, @realtime-framework 

Thanks for getting back so quickly. I've updated my issue with error screenshots

**Comment by realtime-framework** [comment]
We'll probably need to make a few changes to make the module compatible with version 0.9.0
Thanks for the feedback.

**Comment by JakeRawr** [comment]
I did the following to fix the issue:
In terminal
`cd <YourRootProject>/node_modules/react-native/node_modules/react-native-realtimemessaging-ios/`
`rm -rf react-native`
in the same folder, go to package.json, change the react native version to 0.9.0
in the same folder `npm install`

**Comment by realtime-framework** [comment]
Thanks for the feedback @JakeRawr, we'll test for compatibility and update our react native dependency.
